export const PAGES_CONFIG = {
  HOME: '/',
  SERVICES: '/services',
  SERVICES_1C: '/services?q=1c',
  CASES: '/cases',
  ABOUT: '/about',
  BLOG: '/blog',
  CONTACTS: '/contacts',
  POLICY: '/policy',
  MOSCOW: '/moscow',
  SAINT_PETERSBURG: '/saint-petersburg',
  EKATERINBURG: '/ekaterinburg',
  NOVOSIBIRSK: '/novosibirsk',
  KRASNOYARSK: '/krasnoyarsk',
  MINSK: '/minsk',
  BREST: '/brest',
  VITEBSK: '/vitebsk',
  GRODNO: '/grodno',
  HOMEL: '/homel',
  MOHILEV: '/mohilev',
};
