export type ServiceCard = {
  id: string;
  title: string;
  description: string;
  priceFromRub?: number;
  ctaLabel?: string;
  href: string;
  badge?: string;
  tags?: string[];
};
export const SERVICES_TABS = [
  { slug: 'services-1c', title: '1с услуги' },
  { slug: 'web-sites', title: 'Веб разработка' },
  { slug: 'mobile-dev', title: 'Мобильная разработка' },
  { slug: 'server-support', title: 'Сервера и поддержка' },
  { slug: 'crm', title: 'CRM' },
  { slug: 'digitalization', title: 'Цифровизация и автоматизация' },
];

export type ServiceTabSlug = (typeof SERVICES_TABS)[number]['slug'];

export const SERVICES_CARDS: Record<ServiceTabSlug, ServiceCard[]> = {
  'services-1c': [
    {
      id: '1c-implementation',
      title: 'Внедрение 1С:Бухгалтерия',
      description: 'Подбор конфигурации, настройка учёта, перенос данных, обучение пользователей.',
      priceFromRub: 200000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/1c-implementation',
      badge: 'Популярно',
      tags: ['внедрение', 'учёт', 'обучение'],
    },
    {
      id: '1c-refinement',
      title: 'Доработка 1С под бизнес-процессы',
      description: 'Отчёты, печатные формы, обмены, роли/права, оптимизация операций.',
      priceFromRub: 80000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/1c-refinement',
      tags: ['отчёты', 'печатные формы', 'обмены'],
    },
    {
      id: '1c-integration',
      title: 'Интеграции 1С (сайты, CRM, банки)',
      description: 'Двусторонние обмены, очереди, логирование, отказоустойчивость.',
      priceFromRub: 120000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/1c-integration',
      tags: ['API', 'обмен', 'банки'],
    },
    {
      id: '1c-support',
      title: 'Сопровождение и поддержка 1С',
      description: 'SLA, мониторинг, исправление ошибок, обновления, консультации.',
      priceFromRub: 50000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/1c-support',
      tags: ['SLA', 'обновления', 'консультации'],
    },
    {
      id: '1c-performance',
      title: 'Оптимизация производительности 1С',
      description: 'Аудит, узкие места, регламентные задания, SQL-оптимизация, ускорение отчётов.',
      priceFromRub: 90000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/1c-performance',
      tags: ['аудит', 'SQL', 'ускорение'],
    },
    {
      id: '1c-migration',
      title: 'Миграция и обновление конфигураций',
      description: 'Переход на новые релизы, тестовый контур, план отката, документация.',
      priceFromRub: 110000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/1c-migration',
      tags: ['релизы', 'контур', 'откат'],
    },
  ],

  'web-sites': [
    {
      id: 'landing',
      title: 'Лендинг под лидогенерацию',
      description: 'Дизайн, верстка, аналитика, формы, скорость, базовая SEO-структура.',
      priceFromRub: 90000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/landing',
      badge: 'Быстрый запуск',
      tags: ['лендинг', 'аналитика', 'формы'],
    },
    {
      id: 'corporate',
      title: 'Корпоративный сайт',
      description: 'Страницы услуг, кейсы, блог, мультиязычность, админка, контент-модель.',
      priceFromRub: 180000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/corporate',
      tags: ['кейсы', 'блог', 'админка'],
    },
    {
      id: 'ecommerce',
      title: 'Интернет-магазин',
      description: 'Каталог, фильтры, корзина, оплаты, доставки, интеграции и складской учёт.',
      priceFromRub: 350000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/ecommerce',
      badge: 'Сложный проект',
      tags: ['каталог', 'оплаты', 'интеграции'],
    },
    {
      id: 'seo-tech',
      title: 'Техническое SEO и скорость',
      description: 'Core Web Vitals, индексация, микроразметка, карты сайта, логика пагинации.',
      priceFromRub: 70000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/seo-tech',
      tags: ['CWV', 'schema', 'индексация'],
    },
    {
      id: 'web-app',
      title: 'Веб-приложение (личный кабинет)',
      description: 'Роли, авторизация, платежи, интеграции, админ-панель, масштабирование.',
      priceFromRub: 450000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/web-app',
      tags: ['auth', 'roles', 'admin'],
    },
    {
      id: 'support-web',
      title: 'Поддержка и развитие сайта',
      description: 'Пакеты часов, багфиксы, улучшения, контент, A/B, мониторинг.',
      priceFromRub: 40000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/support-web',
      tags: ['поддержка', 'A/B', 'мониторинг'],
    },
  ],

  'mobile-dev': [
    {
      id: 'mvp-mobile',
      title: 'MVP мобильного приложения',
      description: 'Проработка флоу, прототип, разработка, публикация, аналитика событий.',
      priceFromRub: 500000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/mvp-mobile',
      badge: 'Для старта',
      tags: ['MVP', 'публикация', 'аналитика'],
    },
    {
      id: 'ios-android',
      title: 'iOS + Android разработка',
      description: 'Нативно или кроссплатформа, offline, пуши, авторизация, платежи.',
      priceFromRub: 800000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/ios-android',
      tags: ['push', 'offline', 'payments'],
    },
    {
      id: 'mobile-ui',
      title: 'UI/UX для мобильных',
      description: 'Дизайн-система, состояние экранов, адаптив, доступность, тестирование.',
      priceFromRub: 150000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/mobile-ui',
      tags: ['ux', 'design system', 'a11y'],
    },
    {
      id: 'mobile-backend',
      title: 'Backend для приложений',
      description: 'API, авторизация, роли, очереди, хранение файлов, админ-панель.',
      priceFromRub: 350000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/mobile-backend',
      tags: ['API', 'auth', 'storage'],
    },
    {
      id: 'store-setup',
      title: 'Публикация и сопровождение в сторах',
      description: 'Подготовка аккаунтов, сертификаты, сборки, релизы, ASO-основа.',
      priceFromRub: 60000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/store-setup',
      tags: ['release', 'ASO', 'build'],
    },
    {
      id: 'mobile-support',
      title: 'Поддержка и обновления',
      description: 'Crash-аналитика, исправления, совместимость, улучшение производительности.',
      priceFromRub: 70000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/mobile-support',
      tags: ['crash', 'perf', 'updates'],
    },
  ],

  'server-support': [
    {
      id: 'infra-audit',
      title: 'Аудит инфраструктуры',
      description: 'Безопасность, доступы, резервное копирование, мониторинг, план улучшений.',
      priceFromRub: 90000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/infra-audit',
      tags: ['security', 'backup', 'monitoring'],
    },
    {
      id: 'devops-ci',
      title: 'CI/CD и DevOps настройка',
      description: 'Пайплайны, окружения, секреты, деплой, откаты, миграции.',
      priceFromRub: 200000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/devops-ci',
      badge: 'Стабильные релизы',
      tags: ['CI/CD', 'deploy', 'rollback'],
    },
    {
      id: 'monitoring',
      title: 'Мониторинг и алёртинг',
      description: 'Метрики, логи, трассировка, оповещения, дашборды для команды.',
      priceFromRub: 80000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/monitoring',
      tags: ['logs', 'metrics', 'alerts'],
    },
    {
      id: 'backup-dr',
      title: 'Резервное копирование и DR',
      description: 'Политики backup, тест восстановления, RPO/RTO, документация.',
      priceFromRub: 70000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/backup-dr',
      tags: ['DR', 'RPO', 'RTO'],
    },
    {
      id: 'server-support-sla',
      title: 'Поддержка серверов (SLA)',
      description: 'Регламенты, реагирование, обновления, контроль ресурсов, инциденты.',
      priceFromRub: 60000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/server-support-sla',
      tags: ['SLA', 'incidents', 'updates'],
    },
    {
      id: 'cloud-migration',
      title: 'Миграция в облако',
      description: 'Переезд сервисов, сети, безопасность, cost-оптимизация, тестирование.',
      priceFromRub: 250000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/cloud-migration',
      tags: ['cloud', 'network', 'cost'],
    },
  ],

  crm: [
    {
      id: 'crm-impl',
      title: 'Внедрение CRM под отдел продаж',
      description: 'Воронки, этапы, роли, KPI, интеграции, обучение команды.',
      priceFromRub: 200000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/crm-impl',
      badge: 'Популярно',
      tags: ['sales', 'pipelines', 'KPI'],
    },
    {
      id: 'crm-integration',
      title: 'Интеграции CRM (сайт, телефония, почта)',
      description: 'Лиды, звонки, email, мессенджеры, сквозная аналитика.',
      priceFromRub: 120000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/crm-integration',
      tags: ['телефония', 'почта', 'лиды'],
    },
    {
      id: 'crm-automation',
      title: 'Автоматизация CRM-процессов',
      description: 'Роботы, триггеры, задачи, сценарии, уведомления, SLA по сделкам.',
      priceFromRub: 90000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/crm-automation',
      tags: ['automation', 'triggers', 'SLA'],
    },
    {
      id: 'crm-analytics',
      title: 'Отчётность и аналитика',
      description: 'Дашборды, отчёты по менеджерам, источникам, конверсии, прогноз.',
      priceFromRub: 70000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/crm-analytics',
      tags: ['дашборды', 'конверсия', 'прогноз'],
    },
    {
      id: 'crm-migration',
      title: 'Миграция данных в CRM',
      description: 'Очистка, нормализация, импорт, валидация, контроль качества.',
      priceFromRub: 80000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/crm-migration',
      tags: ['миграция', 'качество', 'импорт'],
    },
    {
      id: 'crm-support',
      title: 'Поддержка и развитие CRM',
      description: 'Пакеты часов, улучшения, интеграции, настройка новых процессов.',
      priceFromRub: 50000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/crm-support',
      tags: ['support', 'improvements', 'integrations'],
    },
  ],

  digitalization: [
    {
      id: 'process-audit',
      title: 'Аудит процессов и цифровая карта',
      description: 'Карта процессов, точки потерь, требования, план автоматизации.',
      priceFromRub: 150000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/process-audit',
      badge: 'Стратегия',
      tags: ['аудит', 'требования', 'план'],
    },
    {
      id: 'rpa',
      title: 'RPA-автоматизация',
      description: 'Роботы для рутины: выгрузки, отчёты, перенос данных, уведомления.',
      priceFromRub: 220000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/rpa',
      tags: ['RPA', 'роботы', 'рутина'],
    },
    {
      id: 'integrations',
      title: 'Интеграции систем (API/ETL)',
      description: 'Шины, очереди, согласование данных, логирование и мониторинг.',
      priceFromRub: 250000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/integrations',
      tags: ['API', 'ETL', 'queues'],
    },
    {
      id: 'bi',
      title: 'BI и отчётность',
      description: 'Сбор данных, витрины, KPI, дашборды для руководства.',
      priceFromRub: 300000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/bi',
      tags: ['BI', 'KPI', 'дашборды'],
    },
    {
      id: 'docflow',
      title: 'Электронный документооборот',
      description: 'Согласование, маршруты, подписи, шаблоны, контроль статусов.',
      priceFromRub: 180000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/docflow',
      tags: ['ЭДО', 'согласование', 'подпись'],
    },
    {
      id: 'automation-support',
      title: 'Сопровождение автоматизации',
      description: 'Поддержка процессов, улучшения, контроль ошибок, развитие сценариев.',
      priceFromRub: 70000,
      ctaLabel: 'Подробнее',
      href: '/services/cards/automation-support',
      tags: ['support', 'process', 'improvements'],
    },
  ],
};
